---
name: RPM build in Fedora Copr
on:
  # Builf for push on master and pull request
  push:
    branches: [master]
  pull_request:

jobs:

  build:
    name: Submit a build from Fedora container
    runs-on: ubuntu-latest
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      GITHUB_DEF_BR:  ${{ github.event.repository.default_branch }}
      GITHUB_REF:  ${{ github.ref }}
      GITHUB_HD_REF:  ${{ github.head_ref }}
      GITHUB_BS_REF:  ${{ github.base_ref }}
    strategy:
      matrix:
        oqpython-version: [oq-python37, oq-python38]
    # Run in Fedora container on Ubuntu VM 
        container: ["fedora:latest"]

    container:
      image: ${{ matrix.container }}
    steps:
      - name: Clone Repository 
        uses: actions/checkout@v2

      - name: Install API token for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
        run: |
          mkdir -p "$HOME/.config"
          echo "$API_TOKEN_CONTENT" > "$HOME/.config/copr"
          ls -lrt
          cd ${{ matrix.oqpython-version }} 
          ls -lrt

      - name: Install tooling for source RPM build
        run: |
          dnf -y install @development-tools @rpm-development-tools
          dnf -y install copr-cli make
