---
name: RPM build in Fedora Copr
on:
  # Builf for push on master and pull request
  push:
    branches: [python39]
  pull_request:

jobs:

  build:
    name: Submit a build from Fedora container
    runs-on: ubuntu-latest
    env:
      GITHUB_PULL_REQUEST: ${{ github.event.number }}
      GITHUB_DEF_BR:  ${{ github.event.repository.default_branch }}
      GITHUB_REF:  ${{ github.ref }}
      GITHUB_HD_REF:  ${{ github.head_ref }}
      GITHUB_BS_REF:  ${{ github.base_ref }}
    strategy:
      matrix:
        oqpython-version: [oq-python39]
        epel-release: [epel-7-x86_64, rocky+epel-8-x86_64]
    # Run in Fedora container on Ubuntu VM 

    container:
      image: fedora:36
      options: --privileged
    steps:
      - name: Clone Repository 
        uses: actions/checkout@v2

      - name: Install tooling for source RPM build
        run: |
          dnf -y install @development-tools @rpm-development-tools \
          copr-cli mock make gcc openssl-devel bzip2-devel libffi-devel

      - name: Build RPM from SPEC files
        run: |
          mkdir -p ~/rpmbuild/{RPMS,SOURCES,SPECS,SRPMS}
          cd ${{ matrix.oqpython-version }} 
          cp oq-python.spec ~/rpmbuild/SPECS/
          ls -lrt
          spectool -g -R ~/rpmbuild/SPECS/oq-python.spec 
          rpmbuild -bs  ~/rpmbuild/SPECS/oq-python.spec
          mock -r ${{ matrix.epel-release}} ~/rpmbuild/SRPMS/oq-python39-3.9.12-1.fc36.src.rpm

      - name: Install API token for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
        run: |
          mkdir -p "$HOME/.config"
          echo "$API_TOKEN_CONTENT" > "$HOME/.config/copr"
